# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: The Alan Language Documentation
site_url: https://docs.alan-lang.org
repo_name: alantech/alan
repo_url: https://github.com/alantech/alan
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 
plugins:
  - blog
  - privacy
  - search
  - social
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - tags
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alantech/alan
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/alanlang/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/2a68eK6F
    - icon: fontawesome/brands/mastodon 
      link: https://techhub.social/@ISV_Damocles
