# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: The Alan Programming Language
site_description: A GPGPU-native programming language for the rest of us
site_url: https://docs.alan-lang.org
repo_name: alantech/alan
repo_url: https://github.com/alantech/alan
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 
nav:
  - Home:
    - index.md
  - Getting Started: getting_started/index.md
  - Learn Alan: learn_alan/index.md
  - Reference Guides:
    - reference_guides/index.md
    - overview.md
    - built_ins.md
    - standard_library.md
  - Articles:
    - blog/index.md
plugins:
  - blog:
      blog_dir: blog
  - privacy
  - search
  - social:
      cards_layout_options:
        background_color: "#6c71c4"
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - tags
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alantech/alan
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/alanlang/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/2a68eK6F
    - icon: fontawesome/brands/mastodon 
      link: https://techhub.social/@ISV_Damocles
